
trigger:
  branches:
    include:
      - master  # Trigger on GitHub 'master' or 'main' branch updates

pool:
  vmImage: 'ubuntu-latest'

variables:
  repositoryName: 'hiteshmechlin/timetracker'  # Replace with your actual Docker Hub repository name
  dockerRegistry: 'dockerserviceconnectio'  # Replace with your Docker Hub service connection name

steps:
- task: Docker@2
  inputs:
    containerRegistry: $(dockerRegistry)  # Docker Hub service connection
    repository: $(repositoryName)  # Docker Hub repository name
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'  # Path to your Dockerfile (make sure it is correct)
    tags: |
      $(Build.BuildId)  # Tag the image with build ID
      $(Build.SourceVersion)  # Optionally, tag with commit hash

