trigger: 
  branches:
    include:
      - master  # Triggers pipeline when changes are pushed to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu-based agent for the build

variables:
  dockerRegistryServiceConnection: 'DockerhubConnectionTimeTracker'  # Set this up in Azure DevOps for DockerHub
  imageName: 'hiteshmechlin/timetracker'  # e.g. myusername/myapp
  tag: 'tagone'  # Manually set tag to 'tagone'

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image to DockerHub'
  steps:
    - task: Checkout@1  # Checkout the code from GitHub

    - task: UseNode@1  # Use Node.js to install dependencies (Updated to @1)
      inputs:
        versionSpec: '18.x'  # Specify Node.js version (same as in Dockerfile)
        addToPath: true

    - script: |
        npm install
      displayName: 'Install NPM dependencies'

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)  # Reference DockerHub credentials
        repository: $(imageName)  # DockerHub repository
        tags: |
          $(tag)  # Tag the image with the manually specified tag 'tagone'

    - task: Docker@2
      displayName: 'Push Docker image to DockerHub'
      inputs:
        command: 'push'
        containerRegistry: $(dockerRegistryServiceConnection)  # Reference DockerHub credentials
        repository: $(imageName)  # DockerHub repository
        tags: |
          $(tag)  # Push the image with the tag 'tagone'

#Sample 1