trigger:
  branches:
    include:
      - master  # Trigger only on changes to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Use the Ubuntu hosted image

variables:
  repositoryName: 'hiteshmechlin/timetracker'  # Docker Hub repository name
  dockerRegistry: 'dockerserviceconnection'  # Docker Hub service connection name

steps:
# Step 1: Checkout code from GitHub
- task: Checkout@1
  displayName: 'Checkout Code'
  inputs:
    clean: true  # Clean the repository before checking out

# Step 2: Build and Push Docker Image
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: $(dockerRegistry)  # Docker Hub service connection
    repository: $(repositoryName)  # Docker Hub repository name
    command: 'buildAndPush'  # Command to build and push
    Dockerfile: '**/Dockerfile'  # Path to the Dockerfile
    tags: |
      $(Build.BuildId)  # Tag the image with the build ID
      $(Build.SourceVersion)  # Optionally tag with the commit hash

# Optional Step: (If you want a post-build notification or message)
- script: |
    echo "Docker image $(repositoryName):$(Build.BuildId) successfully built and pushed!"
  displayName: 'Post Build Notification'
