trigger:
  branches:
    include:
      - master  # Trigger pipeline on changes to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build

variables:
  imageName: 'hiteshmechlin/timetracker'  # DockerHub image name
  dockerRegistry: 'docker.io'  # DockerHub registry (optional if you're using default)

steps:
# Debugging variables to ensure they are correct
- script: |
    echo "imageName: $(imageName)"
    echo "dockerRegistry: $(dockerRegistry)"
  displayName: 'Debug Variables'

# Checkout the code from GitHub
- task: Checkout@1  # Checkout task to pull code from the repository

# Set up Docker and build the image
- task: Docker@2
  inputs:
    containerRegistry: 'DockerhubTimeTracker'  # Ensure this service connection exists
    repository: $(imageName)  # DockerHub repository
    command: 'buildAndPush'  # Command to build and push the Docker image
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to your Dockerfile
    tags: |
      $(Build.BuildId)  # Tag the image with the Build ID
      latest  # You can also add `latest` as another tag
    buildContext: $(Build.SourcesDirectory)  # Set the context to the root of the repository

# Optional: Add other tasks as needed
