trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: docker  # Make absolutely sure this is the EXACT name

steps:
- task: Checkout@1
  displayName: 'Checkout code'
  inputs:
    clean: true
  continueOnError: false

- script: |
    echo "Started checking out the code from GitHub..."
  displayName: 'Log: GitHub Checkout Start'

- script: |
    echo "Docker Registry: Docker Hub"
    echo "Build Source Directory: $(Build.SourcesDirectory)"
    echo "Build ID: $(Build.BuildId)"
    echo "Checking Dockerfile presence at $(Build.SourcesDirectory)/Dockerfile"
    ls -al $(Build.SourcesDirectory)
  displayName: 'Log: Debug Variables and Files'

- script: |
    echo "Starting Docker Hub login..."
  displayName: 'Log: Docker Hub Login Start'

- script: |
    echo "$(DOCKER_HUB_PASSWORD)" | docker login -u hiteshmechlin --password-stdin  # EXACT name here
  displayName: 'Docker Hub Login'

- script: |
    docker --version
  displayName: 'Verify Docker Version'

- script: |
    echo "Starting Docker image build and push..."
  displayName: 'Log: Docker Build and Push Start'

- script: |
    echo "Build ID: $(Build.BuildId)"
  displayName: 'Log Build ID'

- script: |
    docker build -t hiteshmechlin/timetracker:$(Build.BuildId) .
    docker push hiteshmechlin/timetracker:$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- script: |
    echo "Docker image build and push completed successfully!"
  displayName: 'Log: Docker Build and Push Completion'
